import type {
  ConsultingRequest,
  DeliveryPod,
  Invoice,
  Professional,
  ProjectOpportunity,
  SpendMonth,
  WorkforceMember,
} from '@/types';

export const PROFESSIONALS: Professional[] = [
  {
    initials: 'SK',
    name: 'Sai K.',
    role: 'Senior Data Engineer',
    community: 'AI & Data',
    specialty: 'Data Engineering',
    skills: ['Databricks', 'PySpark', 'Azure', 'dbt'],
    years: 7,
    zone: 'US Central',
    score: 94,
    rate: 34,
    availableInDays: 0,
    city: 'Hyderabad',
    dimensions: [9.5, 9.2, 9.1, 9.4, 9.5],
    note: 'Strong data modelling and clear cost reasoning on Databricks; explained a platform trade-off clearly and was right.',
    reservation: 'Streaming ingestion exposure is limited.',
    education: 'M.Tech, IIIT Hyderabad',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Flexible'],
  },
  {
    initials: 'AM',
    name: 'Ananya M.',
    role: 'AI / ML Engineer',
    community: 'AI & Data',
    specialty: 'AI & ML',
    skills: ['GenAI', 'RAG', 'Python', 'LangGraph'],
    years: 8,
    zone: 'US Eastern',
    score: 92,
    rate: 38,
    availableInDays: 1,
    city: 'Bengaluru',
    dimensions: [9.3, 9.1, 8.9, 9.0, 9.2],
    note: 'Builds task-specific evaluation sets before optimising; direct about model limitations.',
    reservation: 'Fine-tuning experience is narrower than the profile implies.',
    education: 'M.S., IIIT Hyderabad',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Flexible', 'Project-Based'],
  },
  {
    initials: 'RV',
    name: 'Rahul V.',
    role: 'Data Architect',
    community: 'AI & Data',
    specialty: 'Data Engineering',
    skills: ['Snowflake', 'dbt', 'AWS', 'Airflow'],
    years: 9,
    zone: 'US Central',
    score: 91,
    rate: 42,
    availableInDays: 0,
    city: 'Pune',
    dimensions: [9.2, 9.0, 9.4, 8.8, 9.1],
    note: 'Explains warehouse sizing and cost trade-offs clearly.',
    reservation: 'Prefers to own architecture end to end - pair with an existing lead.',
    education: 'B.Tech, NIT Trichy',
    employment: '4 prior employers confirmed',
    models: ['Dedicated', 'Specialist Experts', 'Flexible'],
  },
  {
    initials: 'MS',
    name: 'Meera S.',
    role: 'Fabric Specialist',
    community: 'AI & Data',
    specialty: 'Data Engineering',
    skills: ['Microsoft Fabric', 'Power BI', 'DAX', 'Synapse'],
    years: 6,
    zone: 'UK',
    score: 96,
    rate: 36,
    availableInDays: 3,
    city: 'Bengaluru',
    dimensions: [9.7, 9.5, 9.4, 9.6, 9.6],
    note: 'Rare depth on Fabric capacity planning, with real cost comparisons.',
    reservation: 'Limited exposure outside the Microsoft stack.',
    education: 'B.E., RVCE',
    employment: '2 prior employers confirmed',
    models: ['Dedicated', 'Specialist Experts', 'Flexible'],
  },
  {
    initials: 'RT',
    name: 'Rohan T.',
    role: 'Senior Cloud Architect',
    community: 'Cloud & DevOps',
    specialty: 'Cloud & DevOps',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'FinOps'],
    years: 10,
    zone: 'US Central',
    score: 92,
    rate: 40,
    availableInDays: 0,
    city: 'Pune',
    dimensions: [9.3, 9.4, 9.5, 8.8, 9.2],
    note: 'Diagnosed an outage by reasoning about blast radius rather than restarting services.',
    reservation: 'Service-mesh depth is limited.',
    education: 'B.E., COEP',
    employment: '4 prior employers confirmed',
    models: ['Dedicated', 'Specialist Experts'],
  },
  {
    initials: 'PK',
    name: 'Prashanth K.',
    role: 'GenAI Engineer',
    community: 'AI & Data',
    specialty: 'AI & ML',
    skills: ['LLMs', 'Agents', 'Evals', 'Python'],
    years: 6,
    zone: 'US Central',
    score: 90,
    rate: 36,
    availableInDays: 0,
    city: 'Hyderabad',
    dimensions: [9.2, 9.0, 8.7, 9.1, 8.9],
    note: 'Designs guardrails and evaluations before shipping; direct about untested claims.',
    reservation: 'Infrastructure-side experience is thinner than application-side.',
    education: 'M.S., IIIT Hyderabad',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Flexible', 'Project-Based'],
  },
  {
    initials: 'DK',
    name: 'Divya K.',
    role: 'QA Automation Engineer',
    community: 'Digital Engineering',
    specialty: 'Quality Engineering',
    skills: ['Playwright', 'Selenium', 'Python', 'CI'],
    years: 5,
    zone: 'US Pacific',
    score: 84,
    rate: 22,
    availableInDays: 5,
    city: 'Hyderabad',
    dimensions: [8.6, 8.4, 8.0, 8.7, 8.5],
    note: 'Strong test design and structured approach.',
    reservation: 'Limited exposure to API-layer and contract testing.',
    education: 'B.Tech, JNTU',
    employment: '2 prior employers confirmed',
    models: ['Dedicated', 'Flexible', 'Project-Based'],
  },
  {
    initials: 'SG',
    name: 'Shiva G.',
    role: 'Frontend Engineer',
    community: 'Digital Engineering',
    specialty: 'Frontend Engineering',
    skills: ['React', 'TypeScript', 'Next.js'],
    years: 4,
    zone: 'US Eastern',
    score: 82,
    rate: 24,
    availableInDays: 0,
    city: 'Chennai',
    dimensions: [8.4, 8.0, 7.7, 8.5, 8.3],
    note: 'Clean component architecture and a real testing instinct.',
    reservation: 'State-management at scale is still developing.',
    education: 'B.E., Anna University',
    employment: '2 prior employers confirmed',
    models: ['Dedicated', 'Flexible', 'Project-Based'],
  },
  {
    initials: 'AR',
    name: 'Ananya R.',
    role: 'ServiceNow Developer',
    community: 'Enterprise Platforms',
    specialty: 'ServiceNow',
    skills: ['ITSM', 'ITOM', 'Flow Designer'],
    years: 5,
    zone: 'UK',
    score: 87,
    rate: 26,
    availableInDays: 0,
    city: 'Bengaluru',
    dimensions: [8.9, 8.6, 8.7, 8.8, 8.6],
    note: "Configuration-first by default; explains why a customization shouldn't be built.",
    reservation: 'ITOM discovery exposure is light.',
    education: 'B.E., RVCE',
    employment: '2 prior employers confirmed',
    models: ['Dedicated', 'Flexible'],
  },
  {
    initials: 'DW',
    name: 'Deepak W.',
    role: 'SAP ABAP Consultant',
    community: 'Enterprise Platforms',
    specialty: 'SAP',
    skills: ['ABAP', 'S/4HANA', 'BTP', 'Fiori'],
    years: 11,
    zone: 'US Eastern',
    score: 86,
    rate: 42,
    availableInDays: 0,
    city: 'Pune',
    dimensions: [8.9, 8.5, 8.7, 8.6, 8.4],
    note: 'Two full-cycle brownfield migrations; can quantify the cost of a modification.',
    reservation: 'BTP integration patterns are recent rather than deep.',
    education: 'B.E., Pune University',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Specialist Experts'],
  },
  {
    initials: 'KM',
    name: 'Kavya M.',
    role: 'Senior Backend Engineer',
    community: 'Digital Engineering',
    specialty: 'Backend Engineering',
    skills: ['Java', 'Spring Boot', 'Kafka'],
    years: 9,
    zone: 'US Pacific',
    score: 89,
    rate: 34,
    availableInDays: 0,
    city: 'Bengaluru',
    dimensions: [9.1, 8.9, 8.8, 8.6, 9.0],
    note: 'Designs for idempotency and back-pressure without prompting.',
    reservation: 'Concise in discussion; strongest in written design docs.',
    education: 'B.E., BMS College',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Flexible'],
  },
  {
    initials: 'JK',
    name: 'Jaya K.',
    role: 'Backend Engineer',
    community: 'Digital Engineering',
    specialty: 'Backend Engineering',
    skills: ['Node.js', 'PostgreSQL', 'APIs'],
    years: 3.5,
    zone: 'US Pacific',
    score: 79,
    rate: 21,
    availableInDays: 0,
    city: 'Pune',
    dimensions: [8.0, 7.8, 7.4, 8.1, 7.9],
    note: 'Clear, well-tested service code and good clarifying questions.',
    reservation: 'Distributed-systems reasoning is early; pairs well with a senior.',
    education: 'B.Tech, VIT',
    employment: '1 prior employer confirmed',
    models: ['Flexible', 'Project-Based'],
  },
  {
    initials: 'AH',
    name: 'Arjun H.',
    role: 'Security Engineer',
    community: 'Transformation & Automation',
    specialty: 'Cybersecurity',
    skills: ['SIEM', 'IAM', 'Cloud security'],
    years: 9,
    zone: 'US Mountain',
    score: 85,
    rate: 36,
    availableInDays: 1,
    city: 'Hyderabad',
    dimensions: [8.8, 8.7, 8.4, 8.3, 8.6],
    note: 'Writes detections that reduce noise; explains risk in terms of consequence.',
    reservation: 'Application security depth is lighter than SOC and IAM.',
    education: 'B.Tech, JNTU',
    employment: '3 prior employers confirmed',
    models: ['Dedicated', 'Specialist Experts', 'Project-Based'],
  },
  {
    initials: 'NP',
    name: 'Nikhil P.',
    role: 'Salesforce Developer',
    community: 'Enterprise Platforms',
    specialty: 'Salesforce',
    skills: ['Apex', 'LWC', 'CPQ', 'Flow'],
    years: 6,
    zone: 'UK',
    score: 83,
    rate: 28,
    availableInDays: 2,
    city: 'Chennai',
    dimensions: [8.5, 8.2, 8.0, 8.6, 8.4],
    note: 'Knows when Flow beats Apex and says so.',
    reservation: 'Data Cloud exposure is limited.',
    education: 'B.E., Anna University',
    employment: '2 prior employers confirmed',
    models: ['Dedicated', 'Flexible', 'Project-Based'],
  },
];

export const INITIAL_PODS: DeliveryPod[] = [
  {
    name: 'Data Modernization Pod',
    team: [0, 2, 6, 7, 11],
    lead: 2,
    owner: 'Alex R.',
    status: 'green',
    sprint: 8,
    velocity: [38, 44, 47, 52, 51, 58, 61, 63],
    commit: [0.82, 0.9, 0.88, 0.94, 0.9, 0.95, 0.93, 0.96],
    start: 'Jun 2026',
    model: 'Managed Delivery Pod',
    fee: 71,
  },
  {
    name: 'AI Discovery -> Build',
    team: [1, 6],
    lead: 1,
    owner: 'Priya T.',
    status: 'amber',
    sprint: 3,
    velocity: [18, 24, 27],
    commit: [0.7, 0.85, 0.88],
    start: 'Aug 2026',
    model: 'Fixed-Scope Project',
    fee: 32,
  },
  {
    name: 'Fabric Migration',
    team: [3, 0],
    lead: 3,
    owner: 'Sam O.',
    status: 'green',
    sprint: 5,
    velocity: [22, 26, 29, 31, 33],
    commit: [0.86, 0.9, 0.92, 0.94, 0.94],
    start: 'Jul 2026',
    model: 'Managed Delivery Pod',
    fee: 38,
  },
];

export const INITIAL_REQUESTS: ConsultingRequest[] = [
  { title: 'AI readiness assessment', type: 'Discovery & Assessment', stage: 2, owner: 'Priya T.', due: 'Oct 3' },
  {
    title: 'Snowflake to Databricks migration plan',
    type: 'Discovery & Assessment',
    stage: 1,
    owner: 'Alex R.',
    due: 'Oct 10',
  },
  { title: 'S/4HANA clean-core review', type: 'Specialist Experts', stage: 3, owner: 'Sam O.', due: 'Sep 26' },
  {
    title: 'Security posture baseline',
    type: 'Advisory Engagement',
    stage: 0,
    owner: 'Priya T.',
    due: 'To be scheduled',
  },
  { title: 'Data platform cost review', type: 'Specialist Experts', stage: 4, owner: 'Alex R.', due: 'Delivered' },
];

export const INITIAL_PROJECTS: ProjectOpportunity[] = [
  {
    title: 'RAG architecture review',
    hours: 'up to 16 hrs',
    rate: 'Agreed on scope',
    zone: 'Any',
    skills: ['RAG', 'Evaluation'],
    status: 'Open',
    applicants: 4,
  },
  {
    title: 'Databricks cost review',
    hours: 'up to 20 hrs',
    rate: 'Agreed on scope',
    zone: 'US Central',
    skills: ['Databricks', 'FinOps'],
    status: 'Open',
    applicants: 2,
  },
  {
    title: 'Automated test suite, checkout flow',
    hours: 'up to 30 hrs',
    rate: 'Agreed on scope',
    zone: 'US Pacific',
    skills: ['Playwright', 'TypeScript'],
    status: 'Matched',
    applicants: 5,
  },
  {
    title: 'dbt model refactor and tests',
    hours: 'up to 24 hrs',
    rate: 'Agreed on scope',
    zone: 'US Eastern',
    skills: ['dbt', 'Snowflake'],
    status: 'In progress',
    applicants: 3,
  },
];

export const INITIAL_WORKFORCE: WorkforceMember[] = [
  { professionalIndex: 0, status: 'live', hours: 40, pending: true, since: 'Jun 2026', model: 'Dedicated' },
  { professionalIndex: 3, status: 'trial', hours: 6, pending: false, since: '3 days ago', model: 'Flexible' },
  { professionalIndex: 8, status: 'live', hours: 38, pending: true, since: 'Aug 2026', model: 'Dedicated' },
  { professionalIndex: 4, status: 'live', hours: 12, pending: false, since: 'Sep 2026', model: 'Specialist Experts' },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    number: 'INV-2026-041',
    period: 'Aug 2026',
    amount: 118.4,
    status: 'Paid',
    lines: { Consulting: 18, Delivery: 71, Talent: 29.4 },
  },
  {
    number: 'INV-2026-052',
    period: 'Sep 2026',
    amount: 132.9,
    status: 'Due Oct 15',
    lines: { Consulting: 24.4, Delivery: 70, Talent: 38.5 },
  },
];

export const SPEND: SpendMonth[] = [
  { month: 'Apr', consulting: 0, delivery: 0, talent: 21.2 },
  { month: 'May', consulting: 18, delivery: 0, talent: 26.8 },
  { month: 'Jun', consulting: 6.4, delivery: 71, talent: 28.1 },
  { month: 'Jul', consulting: 0, delivery: 109, talent: 29.4 },
  { month: 'Aug', consulting: 18, delivery: 71, talent: 29.4 },
  { month: 'Sep', consulting: 24.4, delivery: 70, talent: 38.5 },
];
