import { z } from 'zod';

const optionalNumber = z.preprocess(
  (v) => (v === '' || v === null || v === undefined || (typeof v === 'number' && Number.isNaN(v)) ? undefined : Number(v)),
  z.number().optional().nullable(),
);

export const skillEntrySchema = z.object({
  skillCommunityId: z.preprocess((v) => Number(v), z.number().int().positive('Select a community')),
  proficiencyLevel: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT']),
  yearsExperience: optionalNumber,
  isPrimary: z.boolean(),
  notes: z.string().max(5000).optional().nullable(),
  deletedAt: z.string().optional().nullable(),
});

/** All Candidate + CandidateSkill + related wizard fields (Prisma-aligned). */
export const candidateWizardSchema = z.object({
  organizationId: z.preprocess((v) => Number(v), z.number().int().positive()),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  email: z.string().email('Invalid email').max(255),
  phone: z.string().max(30).optional().nullable(),
  location: z.string().max(255).optional().nullable(),
  linkedinUrl: z.string().max(500).optional().nullable(),
  photoUrl: z.string().max(500).optional().nullable(),
  source: z.enum(['DIRECT', 'REFERRAL', 'JOB_BOARD', 'LINKEDIN', 'AGENCY', 'INTERNAL', 'OTHER']),
  headline: z.string().max(255).optional().nullable(),
  summary: z.string().max(10000).optional().nullable(),
  yearsExperience: optionalNumber,
  primarySkillCommunityId: optionalNumber,
  status: z.enum(['NEW', 'ACTIVE', 'INACTIVE', 'PLACED', 'DO_NOT_CONTACT']),
  visibility: z.enum(['DRAFT', 'PUBLISHED', 'HIDDEN']),
  approvalStatus: z.enum(['PENDING', 'APPROVED', 'REJECTED']),
  publishedAt: z.string().optional().nullable(),
  hiddenAt: z.string().optional().nullable(),
  approvedAt: z.string().optional().nullable(),
  approvedById: optionalNumber,
  rejectedAt: z.string().optional().nullable(),
  rejectedById: optionalNumber,
  rejectionReason: z.string().max(500).optional().nullable(),
  availableFrom: z.string().optional().nullable(),
  timezone: z.string().max(100).optional().nullable(),
  noticePeriodDays: optionalNumber,
  hoursPerWeek: optionalNumber,
  preferredEngagement: z
    .enum(['FULL_TIME', 'PART_TIME', 'CONTRACT', 'FREELANCE'])
    .optional()
    .nullable(),
  blackoutDates: z.string().optional().nullable(),
  availabilityNotes: z.string().max(2000).optional().nullable(),
  expectedRate: optionalNumber,
  currency: z.string().length(3).optional().nullable(),
  payRate: optionalNumber,
  billRate: optionalNumber,
  pricingEffectiveFrom: z.string().optional().nullable(),
  pricingNotes: z.string().max(2000).optional().nullable(),
  resumeDocumentId: optionalNumber,
  profileImageDocumentId: optionalNumber,
  introVideoDocumentId: optionalNumber,
  resumeFileName: z.string().optional().nullable(),
  profileImageFileName: z.string().optional().nullable(),
  introVideoFileName: z.string().optional().nullable(),
  createdAt: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  deletedAt: z.string().optional().nullable(),
  skills: z.array(skillEntrySchema).min(0),
});

export type CandidateWizardValues = z.infer<typeof candidateWizardSchema>;

export const candidateWizardDefaults: CandidateWizardValues = {
  organizationId: 1,
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  location: '',
  linkedinUrl: '',
  photoUrl: '',
  source: 'LINKEDIN',
  headline: '',
  summary: '',
  yearsExperience: undefined,
  primarySkillCommunityId: undefined,
  status: 'NEW',
  visibility: 'DRAFT',
  approvalStatus: 'PENDING',
  publishedAt: '',
  hiddenAt: '',
  approvedAt: '',
  approvedById: undefined,
  rejectedAt: '',
  rejectedById: undefined,
  rejectionReason: '',
  availableFrom: '',
  timezone: 'America/New_York',
  noticePeriodDays: 14,
  hoursPerWeek: 40,
  preferredEngagement: 'CONTRACT',
  blackoutDates: '',
  availabilityNotes: '',
  expectedRate: undefined,
  currency: 'USD',
  payRate: undefined,
  billRate: undefined,
  pricingEffectiveFrom: '',
  pricingNotes: '',
  resumeDocumentId: undefined,
  profileImageDocumentId: undefined,
  introVideoDocumentId: undefined,
  resumeFileName: '',
  profileImageFileName: '',
  introVideoFileName: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: '',
  skills: [
    {
      skillCommunityId: 1,
      proficiencyLevel: 'INTERMEDIATE',
      yearsExperience: undefined,
      isPrimary: true,
      notes: '',
      deletedAt: '',
    },
  ],
};

export const WIZARD_STEPS = [
  {
    id: 'personal',
    label: 'Personal',
    description: 'Identity, contact, and source',
    fields: [
      'organizationId',
      'firstName',
      'lastName',
      'email',
      'phone',
      'location',
      'linkedinUrl',
      'photoUrl',
      'source',
    ] as const,
  },
  {
    id: 'professional',
    label: 'Professional',
    description: 'Profile, status, and approval workflow',
    fields: [
      'headline',
      'summary',
      'yearsExperience',
      'primarySkillCommunityId',
      'status',
      'visibility',
      'approvalStatus',
      'publishedAt',
      'hiddenAt',
      'approvedAt',
      'approvedById',
      'rejectedAt',
      'rejectedById',
      'rejectionReason',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ] as const,
  },
  {
    id: 'skills',
    label: 'Skills',
    description: 'Skill communities and proficiency',
    fields: ['skills', 'primarySkillCommunityId'] as const,
  },
  {
    id: 'availability',
    label: 'Availability',
    description: 'Start date, timezone, and schedule',
    fields: [
      'availableFrom',
      'timezone',
      'noticePeriodDays',
      'hoursPerWeek',
      'preferredEngagement',
      'blackoutDates',
      'availabilityNotes',
    ] as const,
  },
  {
    id: 'pricing',
    label: 'Pricing',
    description: 'Expected, pay, and bill rates',
    fields: [
      'expectedRate',
      'currency',
      'payRate',
      'billRate',
      'pricingEffectiveFrom',
      'pricingNotes',
    ] as const,
  },
  {
    id: 'upload',
    label: 'Upload Resume',
    description: 'Resume, profile image, and intro video',
    fields: [
      'resumeDocumentId',
      'profileImageDocumentId',
      'introVideoDocumentId',
      'resumeFileName',
      'profileImageFileName',
      'introVideoFileName',
    ] as const,
  },
  {
    id: 'review',
    label: 'Review',
    description: 'Confirm all fields before submit',
    fields: [] as const,
  },
] as const;

export type WizardStepId = (typeof WIZARD_STEPS)[number]['id'];

export const DRAFT_STORAGE_KEY = 'bestal-candidate-wizard-draft';

export const FIELD_LABELS: Record<keyof CandidateWizardValues, string> = {
  organizationId: 'Organization ID',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  phone: 'Phone',
  location: 'Location',
  linkedinUrl: 'LinkedIn URL',
  photoUrl: 'Profile Photo URL',
  source: 'Source',
  headline: 'Headline',
  summary: 'Summary',
  yearsExperience: 'Years Experience',
  primarySkillCommunityId: 'Primary Skill Community ID',
  status: 'Status',
  visibility: 'Visibility',
  approvalStatus: 'Approval Status',
  publishedAt: 'Published At',
  hiddenAt: 'Hidden At',
  approvedAt: 'Approved At',
  approvedById: 'Approved By ID',
  rejectedAt: 'Rejected At',
  rejectedById: 'Rejected By ID',
  rejectionReason: 'Rejection Reason',
  availableFrom: 'Available From',
  timezone: 'Timezone',
  noticePeriodDays: 'Notice Period (days)',
  hoursPerWeek: 'Hours Per Week',
  preferredEngagement: 'Preferred Engagement',
  blackoutDates: 'Blackout Dates',
  availabilityNotes: 'Availability Notes',
  expectedRate: 'Expected Rate',
  currency: 'Currency',
  payRate: 'Pay Rate',
  billRate: 'Bill Rate',
  pricingEffectiveFrom: 'Pricing Effective From',
  pricingNotes: 'Pricing Notes',
  resumeDocumentId: 'Resume Document ID',
  profileImageDocumentId: 'Profile Image Document ID',
  introVideoDocumentId: 'Intro Video Document ID',
  resumeFileName: 'Resume File',
  profileImageFileName: 'Profile Image File',
  introVideoFileName: 'Intro Video File',
  createdAt: 'Created At',
  updatedAt: 'Updated At',
  deletedAt: 'Deleted At',
  skills: 'Skills',
};
