import type { MockApproval } from './types.js';

export const approvals = [
  {
    id: 1,
    type: 'SHORTLIST',
    title: 'Approve DevOps shortlist',
    description: 'Review 2 vetted DevOps engineers for JPMorgan cloud migration initiative.',
    status: 'PENDING',
    requestedBy: 'Angela Torres',
    requestedAt: '2026-06-06T09:00:00Z',
    reviewedBy: null,
    reviewedAt: null,
    entityId: 2,
    clientId: 3,
    clientName: 'JPMorgan Chase',
  },
  {
    id: 2,
    type: 'CANDIDATE',
    title: 'Approve Michael Brooks profile',
    description: 'Security architect candidate for FedRAMP initiative. CISSP certified with 15 years experience.',
    status: 'PENDING',
    requestedBy: 'Angela Torres',
    requestedAt: '2026-06-28T16:30:00Z',
    reviewedBy: null,
    reviewedAt: null,
    entityId: 6,
    clientId: 3,
    clientName: 'JPMorgan Chase',
  },
  {
    id: 3,
    type: 'DEPLOYMENT',
    title: 'Confirm Alexandra Petrov deployment',
    description: 'Staff Full-Stack Engineer at Stripe Payments. Rate: $155/hr. Start: Jul 15, 2026.',
    status: 'APPROVED',
    requestedBy: 'Rachel Kim',
    requestedAt: '2026-06-20T10:00:00Z',
    reviewedBy: 'Sarah Chen',
    reviewedAt: '2026-06-22T14:00:00Z',
    entityId: 4,
    clientId: 1,
    clientName: 'Stripe',
  },
  {
    id: 4,
    type: 'TRIAL',
    title: 'Trial period — Carlos Mendez',
    description: '2-week paid trial for Lead Mobile Engineer role at Airbnb Experiences team.',
    status: 'APPROVED',
    requestedBy: 'Tom Bradley',
    requestedAt: '2026-06-15T11:00:00Z',
    reviewedBy: 'Jennifer Walsh',
    reviewedAt: '2026-06-17T09:30:00Z',
    entityId: 4,
    clientId: 5,
    clientName: 'Airbnb',
  },
  {
    id: 5,
    type: 'SHORTLIST',
    title: 'Approve React engineers shortlist',
    description: '3 senior React engineers shortlisted for Stripe Payments platform rebuild.',
    status: 'APPROVED',
    requestedBy: 'Rachel Kim',
    requestedAt: '2026-06-10T10:00:00Z',
    reviewedBy: 'Sarah Chen',
    reviewedAt: '2026-06-11T16:00:00Z',
    entityId: 1,
    clientId: 1,
    clientName: 'Stripe',
  },
  {
    id: 6,
    type: 'CANDIDATE',
    title: 'Reject Daniel Kowalski visibility',
    description: 'Client feedback: backend-focused profile does not meet frontend requirements for this role.',
    status: 'REJECTED',
    requestedBy: 'Sarah Chen',
    requestedAt: '2026-06-29T15:00:00Z',
    reviewedBy: 'Rachel Kim',
    reviewedAt: '2026-06-29T16:00:00Z',
    entityId: 8,
    clientId: 1,
    clientName: 'Stripe',
  },
] as const satisfies readonly MockApproval[];

export type Approvals = typeof approvals;
