import type { MockAuditLog } from './types.js';

export const auditLogs = [
  {
    id: 1,
    action: 'APPROVE',
    entityType: 'Candidate',
    entityId: 1,
    actorName: 'Jordan Hayes',
    actorEmail: 'admin@bestal.com',
    summary: 'Approved candidate Alexandra Petrov for client visibility',
    ipAddress: '192.168.1.100',
    createdAt: '2026-06-10T11:30:00Z',
  },
  {
    id: 2,
    action: 'CREATE',
    entityType: 'Shortlist',
    entityId: 1,
    actorName: 'Rachel Kim',
    actorEmail: 'rachel.kim@bestal.com',
    summary: 'Created shortlist "Senior React Engineers — Stripe Payments"',
    ipAddress: '10.0.0.45',
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 3,
    action: 'LOGIN',
    entityType: 'User',
    entityId: 8,
    actorName: 'Sarah Chen',
    actorEmail: 'sarah.chen@stripe.com',
    summary: 'Client portal login from Stripe',
    ipAddress: '203.0.113.42',
    createdAt: '2026-06-30T11:00:00Z',
  },
  {
    id: 4,
    action: 'UPDATE',
    entityType: 'InterviewRequest',
    entityId: 2,
    actorName: 'Rachel Kim',
    actorEmail: 'rachel.kim@bestal.com',
    summary: 'Scheduled panel interview for Alexandra Petrov at Stripe',
    ipAddress: '10.0.0.45',
    createdAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 5,
    action: 'EXPORT',
    entityType: 'Shortlist',
    entityId: 2,
    actorName: 'Angela Torres',
    actorEmail: 'angela.torres@bestal.com',
    summary: 'Exported shortlist PDF for JPMorgan Chase review',
    ipAddress: '10.0.0.52',
    createdAt: '2026-06-20T16:45:00Z',
  },
  {
    id: 6,
    action: 'REJECT',
    entityType: 'Candidate',
    entityId: 99,
    actorName: 'David Chen',
    actorEmail: 'david.chen@bestal.com',
    summary: 'Rejected candidate — insufficient technical evaluation score',
    ipAddress: '10.0.0.48',
    createdAt: '2026-06-15T10:20:00Z',
  },
  {
    id: 7,
    action: 'VIEW',
    entityType: 'Candidate',
    entityId: 3,
    actorName: 'Sarah Chen',
    actorEmail: 'sarah.chen@stripe.com',
    summary: 'Viewed candidate profile Priya Sharma via client portal',
    ipAddress: '203.0.113.42',
    createdAt: '2026-06-28T09:15:00Z',
  },
  {
    id: 8,
    action: 'CREATE',
    entityType: 'Deployment',
    entityId: 1,
    actorName: 'Rachel Kim',
    actorEmail: 'rachel.kim@bestal.com',
    summary: 'Created deployment for Priya Sharma at Spotify',
    ipAddress: '10.0.0.45',
    createdAt: '2026-05-28T17:00:00Z',
  },
] as const satisfies readonly MockAuditLog[];

export type AuditLogs = typeof auditLogs;
