import type { MockAvailability } from './types.js';

export const candidateAvailability = [
  {
    candidateId: 1,
    timezone: 'America/New_York',
    noticePeriodDays: 14,
    availableFrom: '2026-07-15',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: ['2026-08-10', '2026-08-11'],
    notes: 'Available for full-time contract. Prefers remote with occasional onsite.',
  },
  {
    candidateId: 2,
    timezone: 'Europe/London',
    noticePeriodDays: 30,
    availableFrom: '2026-08-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: [],
    notes: 'Currently wrapping up Coinbase engagement.',
  },
  {
    candidateId: 3,
    timezone: 'America/Los_Angeles',
    noticePeriodDays: 7,
    availableFrom: '2026-12-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: ['2026-11-24', '2026-11-25', '2026-11-26'],
    notes: 'Active at Spotify until contract end. Open to extension discussions.',
  },
  {
    candidateId: 4,
    timezone: 'America/Mexico_City',
    noticePeriodDays: 14,
    availableFrom: '2026-07-07',
    hoursPerWeek: 32,
    preferredEngagement: 'PART_TIME',
    blackoutDates: [],
    notes: 'Prefers 32-hour weeks. Strong overlap with US Eastern time.',
  },
  {
    candidateId: 5,
    timezone: 'America/Los_Angeles',
    noticePeriodDays: 21,
    availableFrom: '2026-10-15',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: [],
    notes: 'Active deployment at Airbnb.',
  },
  {
    candidateId: 6,
    timezone: 'America/Chicago',
    noticePeriodDays: 7,
    availableFrom: '2026-06-30',
    hoursPerWeek: 40,
    preferredEngagement: 'FULL_TIME',
    blackoutDates: [],
    notes: 'Immediately available. Open to 20-hour pilot engagements.',
  },
  {
    candidateId: 7,
    timezone: 'Asia/Dubai',
    noticePeriodDays: 14,
    availableFrom: '2026-05-01',
    hoursPerWeek: 32,
    preferredEngagement: 'FREELANCE',
    blackoutDates: ['2026-07-01', '2026-07-02'],
    notes: 'Freelance arrangement preferred. 4-hour overlap with US East.',
  },
  {
    candidateId: 8,
    timezone: 'America/New_York',
    noticePeriodDays: 14,
    availableFrom: '2026-07-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: [],
    notes: 'Security clearance in progress.',
  },
  {
    candidateId: 9,
    timezone: 'America/San_Francisco',
    noticePeriodDays: 21,
    availableFrom: '2026-08-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: [],
    notes: 'Product management roles only.',
  },
  {
    candidateId: 10,
    timezone: 'America/New_York',
    noticePeriodDays: 30,
    availableFrom: '2026-08-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: [],
    notes: 'Pending JPMorgan deployment start.',
  },
  {
    candidateId: 11,
    timezone: 'Europe/Berlin',
    noticePeriodDays: 14,
    availableFrom: '2026-07-01',
    hoursPerWeek: 40,
    preferredEngagement: 'CONTRACT',
    blackoutDates: ['2026-08-01', '2026-08-15'],
    notes: 'EU timezone. Remote only.',
  },
  {
    candidateId: 12,
    timezone: 'Asia/Kolkata',
    noticePeriodDays: 7,
    availableFrom: '2026-06-23',
    hoursPerWeek: 40,
    preferredEngagement: 'FULL_TIME',
    blackoutDates: [],
    notes: 'Immediately available. Strong US overlap (EST mornings).',
  },
] as const satisfies readonly MockAvailability[];

export function getAvailabilityForCandidate(candidateId: number): MockAvailability | undefined {
  return candidateAvailability.find((a) => a.candidateId === candidateId);
}

export type CandidateAvailability = typeof candidateAvailability;
