import type { MockBackgroundCheck } from './types.js';

export const backgroundChecks = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    type: 'COMPREHENSIVE',
    status: 'CLEAR',
    requestedBy: 'Rachel Kim',
    requestedAt: '2026-06-12T09:00:00Z',
    completedAt: '2026-06-18T14:00:00Z',
    provider: 'Checkr',
  },
  {
    id: 2,
    candidateId: 2,
    candidateName: 'James Okoro',
    type: 'COMPREHENSIVE',
    status: 'IN_PROGRESS',
    requestedBy: 'Angela Torres',
    requestedAt: '2026-06-25T10:00:00Z',
    completedAt: null,
    provider: 'Sterling',
  },
  {
    id: 3,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    type: 'COMPREHENSIVE',
    status: 'CLEAR',
    requestedBy: 'Rachel Kim',
    requestedAt: '2026-05-15T08:00:00Z',
    completedAt: '2026-05-22T16:00:00Z',
    provider: 'Checkr',
  },
  {
    id: 4,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    type: 'CRIMINAL',
    status: 'PENDING',
    requestedBy: 'Angela Torres',
    requestedAt: '2026-06-28T11:00:00Z',
    completedAt: null,
    provider: 'Sterling',
  },
  {
    id: 5,
    candidateId: 8,
    candidateName: 'Daniel Kowalski',
    type: 'EMPLOYMENT',
    status: 'NOT_STARTED',
    requestedBy: 'David Chen',
    requestedAt: '2026-06-30T09:00:00Z',
    completedAt: null,
    provider: 'Checkr',
  },
  {
    id: 6,
    candidateId: 10,
    candidateName: 'Raj Patel',
    type: 'EDUCATION',
    status: 'CLEAR',
    requestedBy: 'Sarah Mitchell',
    requestedAt: '2026-06-05T14:00:00Z',
    completedAt: '2026-06-10T10:00:00Z',
    provider: 'Checkr',
  },
] as const satisfies readonly MockBackgroundCheck[];

export type BackgroundChecks = typeof backgroundChecks;
