import type { MockCandidate } from './types.js';

const avatar = (name: string, _seed: number) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=0D47A1&color=fff&size=256&bold=true`;

const photo = (id: number) => `https://picsum.photos/seed/bestal-candidate-${id}/400/400`;

export const candidates = [
  {
    id: 1,
    firstName: 'Alexandra',
    lastName: 'Petrov',
    email: 'alexandra.petrov@email.com',
    headline: 'Staff Full-Stack Engineer | React, Node, AWS',
    summary:
      'Former tech lead at a fintech unicorn building payment infrastructure. 10 years shipping production systems at scale.',
    location: 'San Francisco, CA',
    yearsExperience: 10,
    expectedRate: 155,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'LINKEDIN',
    photoUrl: photo(1),
    linkedinUrl: 'https://linkedin.com/in/alexandra-petrov',
    availableFrom: '2026-07-15',
    skills: [
      { skillCommunityId: 1, skillCommunityName: 'Full-Stack Development', proficiencyLevel: 'EXPERT', yearsExperience: 10, isPrimary: true },
      { skillCommunityId: 2, skillCommunityName: 'DevOps & Cloud', proficiencyLevel: 'ADVANCED', yearsExperience: 5, isPrimary: false },
    ],
  },
  {
    id: 2,
    firstName: 'James',
    lastName: 'Okoro',
    email: 'james.okoro@email.com',
    headline: 'Principal DevOps Engineer | Kubernetes, Terraform',
    summary: 'SRE lead with experience at Netflix and Coinbase. Specializes in zero-downtime migrations.',
    location: 'New York, NY',
    yearsExperience: 12,
    expectedRate: 175,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'REFERRAL',
    photoUrl: avatar('James Okoro', 2),
    linkedinUrl: 'https://linkedin.com/in/james-okoro',
    availableFrom: '2026-07-01',
    skills: [
      { skillCommunityId: 2, skillCommunityName: 'DevOps & Cloud', proficiencyLevel: 'EXPERT', yearsExperience: 12, isPrimary: true },
      { skillCommunityId: 6, skillCommunityName: 'Cybersecurity', proficiencyLevel: 'ADVANCED', yearsExperience: 4, isPrimary: false },
    ],
  },
  {
    id: 3,
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@email.com',
    headline: 'Senior ML Engineer | PyTorch, NLP, MLOps',
    summary: 'Built recommendation engines serving 50M+ users. PhD in Computer Science from MIT.',
    location: 'Boston, MA',
    yearsExperience: 8,
    expectedRate: 165,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'DIRECT',
    photoUrl: photo(3),
    linkedinUrl: 'https://linkedin.com/in/priya-sharma-ml',
    availableFrom: '2026-08-01',
    skills: [
      { skillCommunityId: 4, skillCommunityName: 'Machine Learning', proficiencyLevel: 'EXPERT', yearsExperience: 8, isPrimary: true },
      { skillCommunityId: 3, skillCommunityName: 'Data Engineering', proficiencyLevel: 'ADVANCED', yearsExperience: 5, isPrimary: false },
    ],
  },
  {
    id: 4,
    firstName: 'Carlos',
    lastName: 'Mendez',
    email: 'carlos.mendez@email.com',
    headline: 'Lead Mobile Developer | React Native, Swift',
    summary: 'Shipped 12 apps to App Store top charts. Expert in cross-platform and native performance tuning.',
    location: 'Miami, FL',
    yearsExperience: 9,
    expectedRate: 130,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'JOB_BOARD',
    photoUrl: avatar('Carlos Mendez', 4),
    linkedinUrl: 'https://linkedin.com/in/carlos-mendez-mobile',
    availableFrom: '2026-07-20',
    skills: [
      { skillCommunityId: 5, skillCommunityName: 'Mobile Development', proficiencyLevel: 'EXPERT', yearsExperience: 9, isPrimary: true },
      { skillCommunityId: 1, skillCommunityName: 'Full-Stack Development', proficiencyLevel: 'INTERMEDIATE', yearsExperience: 3, isPrimary: false },
    ],
  },
  {
    id: 5,
    firstName: 'Emily',
    lastName: 'Nakamura',
    email: 'emily.nakamura@email.com',
    headline: 'Staff Data Engineer | Spark, Kafka, Snowflake',
    summary: 'Architected data platforms at Airbnb and Uber. Strong in real-time streaming and data governance.',
    location: 'Seattle, WA',
    yearsExperience: 11,
    expectedRate: 170,
    currency: 'USD',
    status: 'PLACED',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'AGENCY',
    photoUrl: photo(5),
    linkedinUrl: 'https://linkedin.com/in/emily-nakamura',
    availableFrom: '2026-10-01',
    skills: [
      { skillCommunityId: 3, skillCommunityName: 'Data Engineering', proficiencyLevel: 'EXPERT', yearsExperience: 11, isPrimary: true },
      { skillCommunityId: 4, skillCommunityName: 'Machine Learning', proficiencyLevel: 'ADVANCED', yearsExperience: 3, isPrimary: false },
    ],
  },
  {
    id: 6,
    firstName: 'Michael',
    lastName: 'Brooks',
    email: 'michael.brooks@email.com',
    headline: 'Security Architect | Zero Trust, FedRAMP',
    summary: 'CISSP-certified architect with 15 years securing enterprise cloud environments.',
    location: 'Washington, DC',
    yearsExperience: 15,
    expectedRate: 190,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'REFERRAL',
    photoUrl: avatar('Michael Brooks', 6),
    linkedinUrl: 'https://linkedin.com/in/michael-brooks-cissp',
    availableFrom: '2026-07-10',
    skills: [
      { skillCommunityId: 6, skillCommunityName: 'Cybersecurity', proficiencyLevel: 'EXPERT', yearsExperience: 15, isPrimary: true },
      { skillCommunityId: 2, skillCommunityName: 'DevOps & Cloud', proficiencyLevel: 'ADVANCED', yearsExperience: 8, isPrimary: false },
    ],
  },
  {
    id: 7,
    firstName: 'Fatima',
    lastName: 'Al-Rashid',
    email: 'fatima.alrashid@email.com',
    headline: 'Senior Frontend Engineer | React, Design Systems',
    summary: 'Built design systems used by 200+ engineers at Shopify. Accessibility and performance advocate.',
    location: 'Toronto, ON',
    yearsExperience: 7,
    expectedRate: 125,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'LINKEDIN',
    photoUrl: photo(7),
    linkedinUrl: 'https://linkedin.com/in/fatima-alrashid',
    availableFrom: '2026-07-05',
    skills: [
      { skillCommunityId: 1, skillCommunityName: 'Full-Stack Development', proficiencyLevel: 'EXPERT', yearsExperience: 7, isPrimary: true },
    ],
  },
  {
    id: 8,
    firstName: 'Daniel',
    lastName: 'Kowalski',
    email: 'daniel.kowalski@email.com',
    headline: 'Backend Engineer | Go, PostgreSQL, gRPC',
    summary: 'High-performance backend specialist. Previously at Google working on distributed systems.',
    location: 'Chicago, IL',
    yearsExperience: 9,
    expectedRate: 145,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'PENDING',
    source: 'DIRECT',
    photoUrl: avatar('Daniel Kowalski', 8),
    linkedinUrl: 'https://linkedin.com/in/daniel-kowalski-go',
    availableFrom: '2026-08-15',
    skills: [
      { skillCommunityId: 1, skillCommunityName: 'Full-Stack Development', proficiencyLevel: 'EXPERT', yearsExperience: 9, isPrimary: true },
      { skillCommunityId: 2, skillCommunityName: 'DevOps & Cloud', proficiencyLevel: 'INTERMEDIATE', yearsExperience: 4, isPrimary: false },
    ],
  },
  {
    id: 9,
    firstName: 'Sofia',
    lastName: 'Andersson',
    email: 'sofia.andersson@email.com',
    headline: 'Product Designer | UX Research, Figma',
    summary: 'Led design for B2B SaaS products at HubSpot. Strong in user research and design systems.',
    location: 'Stockholm, Sweden',
    yearsExperience: 8,
    expectedRate: 115,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'REFERRAL',
    photoUrl: photo(9),
    linkedinUrl: 'https://linkedin.com/in/sofia-andersson-ux',
    availableFrom: '2026-07-25',
    skills: [
      { skillCommunityId: 7, skillCommunityName: 'Product Design', proficiencyLevel: 'EXPERT', yearsExperience: 8, isPrimary: true },
    ],
  },
  {
    id: 10,
    firstName: 'Raj',
    lastName: 'Patel',
    email: 'raj.patel@email.com',
    headline: 'Platform Engineer | Rust, Kubernetes',
    summary: 'Systems programmer building low-latency trading infrastructure. Rust and Go expert.',
    location: 'London, UK',
    yearsExperience: 10,
    expectedRate: 180,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'LINKEDIN',
    photoUrl: avatar('Raj Patel', 10),
    linkedinUrl: 'https://linkedin.com/in/raj-patel-platform',
    availableFrom: '2026-07-01',
    skills: [
      { skillCommunityId: 2, skillCommunityName: 'DevOps & Cloud', proficiencyLevel: 'EXPERT', yearsExperience: 10, isPrimary: true },
      { skillCommunityId: 1, skillCommunityName: 'Full-Stack Development', proficiencyLevel: 'ADVANCED', yearsExperience: 6, isPrimary: false },
    ],
  },
  {
    id: 11,
    firstName: 'Lisa',
    lastName: 'Thompson',
    email: 'lisa.thompson@email.com',
    headline: 'QA Automation Lead | Cypress, Playwright',
    summary: 'Built test automation frameworks for enterprise SaaS. 40% reduction in regression cycles.',
    location: 'Denver, CO',
    yearsExperience: 9,
    expectedRate: 110,
    currency: 'USD',
    status: 'NEW',
    visibility: 'DRAFT',
    approvalStatus: 'PENDING',
    source: 'JOB_BOARD',
    photoUrl: photo(11),
    linkedinUrl: 'https://linkedin.com/in/lisa-thompson-qa',
    availableFrom: '2026-09-01',
    skills: [
      { skillCommunityId: 8, skillCommunityName: 'QA & Test Automation', proficiencyLevel: 'EXPERT', yearsExperience: 9, isPrimary: true },
    ],
  },
  {
    id: 12,
    firstName: 'Wei',
    lastName: 'Zhang',
    email: 'wei.zhang@email.com',
    headline: 'Blockchain Engineer | Solidity, Ethereum',
    summary: 'Smart contract auditor and DeFi protocol developer. Former ConsenSys engineer.',
    location: 'Singapore',
    yearsExperience: 6,
    expectedRate: 160,
    currency: 'USD',
    status: 'ACTIVE',
    visibility: 'PUBLISHED',
    approvalStatus: 'APPROVED',
    source: 'DIRECT',
    photoUrl: avatar('Wei Zhang', 12),
    linkedinUrl: 'https://linkedin.com/in/wei-zhang-blockchain',
    availableFrom: '2026-07-15',
    skills: [
      { skillCommunityId: 9, skillCommunityName: 'Blockchain', proficiencyLevel: 'EXPERT', yearsExperience: 6, isPrimary: true },
      { skillCommunityId: 6, skillCommunityName: 'Cybersecurity', proficiencyLevel: 'ADVANCED', yearsExperience: 3, isPrimary: false },
    ],
  },
] as const satisfies readonly MockCandidate[];

export type Candidates = typeof candidates;
