import type { MockClient } from './types.js';
import { companyLogoUrl } from './company-logos.js';

export const clients = [
  {
    id: 1,
    name: 'Stripe',
    industry: 'Fintech',
    website: 'https://stripe.com',
    logoUrl: companyLogoUrl('Stripe'),
    status: 'ACTIVE',
    accountManager: 'Rachel Kim',
    location: 'San Francisco, CA',
    employeeCount: '8,000+',
    activeDeployments: 24,
    totalSpend: 4_200_000,
    currency: 'USD',
  },
  {
    id: 2,
    name: 'Shopify',
    industry: 'E-commerce',
    website: 'https://shopify.com',
    logoUrl: companyLogoUrl('Shopify'),
    status: 'ACTIVE',
    accountManager: 'Tom Bradley',
    location: 'Ottawa, Canada',
    employeeCount: '10,000+',
    activeDeployments: 18,
    totalSpend: 3_100_000,
    currency: 'USD',
  },
  {
    id: 3,
    name: 'JPMorgan Chase',
    industry: 'Financial Services',
    website: 'https://jpmorganchase.com',
    logoUrl: companyLogoUrl('JPMorgan Chase'),
    status: 'ACTIVE',
    accountManager: 'Angela Torres',
    location: 'New York, NY',
    employeeCount: '300,000+',
    activeDeployments: 42,
    totalSpend: 8_750_000,
    currency: 'USD',
  },
  {
    id: 4,
    name: 'Spotify',
    industry: 'Media & Entertainment',
    website: 'https://spotify.com',
    logoUrl: companyLogoUrl('Spotify'),
    status: 'ACTIVE',
    accountManager: 'Rachel Kim',
    location: 'Stockholm, Sweden',
    employeeCount: '9,000+',
    activeDeployments: 12,
    totalSpend: 2_400_000,
    currency: 'USD',
  },
  {
    id: 5,
    name: 'Airbnb',
    industry: 'Travel & Hospitality',
    website: 'https://airbnb.com',
    logoUrl: companyLogoUrl('Airbnb'),
    status: 'ACTIVE',
    accountManager: 'Tom Bradley',
    location: 'San Francisco, CA',
    employeeCount: '6,800+',
    activeDeployments: 15,
    totalSpend: 2_850_000,
    currency: 'USD',
  },
  {
    id: 6,
    name: 'Palantir',
    industry: 'Enterprise Software',
    website: 'https://palantir.com',
    logoUrl: companyLogoUrl('Palantir'),
    status: 'PROSPECT',
    accountManager: 'Angela Torres',
    location: 'Denver, CO',
    employeeCount: '3,500+',
    activeDeployments: 0,
    totalSpend: 0,
    currency: 'USD',
  },
  {
    id: 7,
    name: 'Coinbase',
    industry: 'Cryptocurrency',
    website: 'https://coinbase.com',
    logoUrl: companyLogoUrl('Coinbase'),
    status: 'ACTIVE',
    accountManager: 'Rachel Kim',
    location: 'Remote-first',
    employeeCount: '4,500+',
    activeDeployments: 8,
    totalSpend: 1_650_000,
    currency: 'USD',
  },
] as const satisfies readonly MockClient[];

export type Clients = typeof clients;
