import type { MockDeployment } from './types.js';

export const deployments = [
  {
    id: 1,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    clientId: 4,
    clientName: 'Spotify',
    title: 'Senior ML Engineer — Recommendations',
    status: 'ACTIVE',
    placementType: 'CONTRACT',
    startDate: '2026-06-01',
    endDate: '2026-12-01',
    rate: 165,
    currency: 'USD',
    hoursPerWeek: 40,
  },
  {
    id: 2,
    candidateId: 5,
    candidateName: 'Emily Nakamura',
    clientId: 5,
    clientName: 'Airbnb',
    title: 'Staff Data Engineer — Analytics Platform',
    status: 'ACTIVE',
    placementType: 'CONTRACT',
    startDate: '2026-04-15',
    endDate: '2026-10-15',
    rate: 170,
    currency: 'USD',
    hoursPerWeek: 40,
  },
  {
    id: 3,
    candidateId: 2,
    candidateName: 'James Okoro',
    clientId: 7,
    clientName: 'Coinbase',
    title: 'Principal DevOps Engineer',
    status: 'COMPLETED',
    placementType: 'CONTRACT',
    startDate: '2025-09-01',
    endDate: '2026-05-31',
    rate: 175,
    currency: 'USD',
    hoursPerWeek: 40,
  },
  {
    id: 4,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    clientId: 1,
    clientName: 'Stripe',
    title: 'Staff Full-Stack Engineer — Payments',
    status: 'PENDING',
    placementType: 'CONTRACT',
    startDate: '2026-07-15',
    endDate: '2027-01-15',
    rate: 155,
    currency: 'USD',
    hoursPerWeek: 40,
  },
  {
    id: 5,
    candidateId: 7,
    candidateName: 'Fatima Al-Rashid',
    clientId: 2,
    clientName: 'Shopify',
    title: 'Senior Frontend Engineer — Design Systems',
    status: 'ACTIVE',
    placementType: 'FREELANCE',
    startDate: '2026-05-01',
    endDate: null,
    rate: 125,
    currency: 'USD',
    hoursPerWeek: 32,
  },
  {
    id: 6,
    candidateId: 10,
    candidateName: 'Raj Patel',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    title: 'Platform Engineer — Trading Infrastructure',
    status: 'ON_HOLD',
    placementType: 'CONTRACT',
    startDate: '2026-08-01',
    endDate: '2027-02-01',
    rate: 180,
    currency: 'USD',
    hoursPerWeek: 40,
  },
] as const satisfies readonly MockDeployment[];

export type Deployments = typeof deployments;
