import type { MockDocument } from './types.js';

export const documents = [
  {
    id: 1,
    entityType: 'CANDIDATE',
    entityId: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    kind: 'RESUME',
    fileName: 'alexandra-petrov-resume.pdf',
    fileSizeKb: 284,
    mimeType: 'application/pdf',
    uploadedBy: 'Rachel Kim',
    uploadedAt: '2026-05-12T09:15:00Z',
    status: 'VERIFIED',
  },
  {
    id: 2,
    entityType: 'CANDIDATE',
    entityId: 2,
    candidateId: 2,
    candidateName: 'James Okoro',
    kind: 'RESUME',
    fileName: 'james-okoro-cv.pdf',
    fileSizeKb: 312,
    mimeType: 'application/pdf',
    uploadedBy: 'Tom Bradley',
    uploadedAt: '2026-04-28T14:22:00Z',
    status: 'VERIFIED',
  },
  {
    id: 3,
    entityType: 'CANDIDATE',
    entityId: 3,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    kind: 'RESUME',
    fileName: 'priya-sharma-resume.pdf',
    fileSizeKb: 198,
    mimeType: 'application/pdf',
    uploadedBy: 'Rachel Kim',
    uploadedAt: '2026-06-01T11:00:00Z',
    status: 'VERIFIED',
  },
  {
    id: 4,
    entityType: 'EVALUATION',
    entityId: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    kind: 'EVALUATION_FORM',
    fileName: 'eval-fullstack-staff-v2.pdf',
    fileSizeKb: 156,
    mimeType: 'application/pdf',
    uploadedBy: 'Rachel Kim',
    uploadedAt: '2026-05-20T16:45:00Z',
    status: 'VERIFIED',
  },
  {
    id: 5,
    entityType: 'EVALUATION',
    entityId: 3,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    kind: 'EVALUATION_FORM',
    fileName: 'eval-ml-senior.pdf',
    fileSizeKb: 142,
    mimeType: 'application/pdf',
    uploadedBy: 'Tom Bradley',
    uploadedAt: '2026-06-03T10:30:00Z',
    status: 'PROCESSING',
  },
  {
    id: 6,
    entityType: 'BACKGROUND_CHECK',
    entityId: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    kind: 'BGV_FORM',
    fileName: 'bgv-consent-alexandra-petrov.pdf',
    fileSizeKb: 89,
    mimeType: 'application/pdf',
    uploadedBy: 'Rachel Kim',
    uploadedAt: '2026-05-22T08:00:00Z',
    status: 'VERIFIED',
  },
  {
    id: 7,
    entityType: 'BACKGROUND_CHECK',
    entityId: 4,
    candidateId: 4,
    candidateName: 'Sofia Martinez',
    kind: 'BGV_FORM',
    fileName: 'bgv-consent-sofia-martinez.pdf',
    fileSizeKb: 91,
    mimeType: 'application/pdf',
    uploadedBy: 'Tom Bradley',
    uploadedAt: '2026-06-10T13:15:00Z',
    status: 'UPLOADED',
  },
  {
    id: 8,
    entityType: 'CANDIDATE',
    entityId: 6,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    kind: 'RESUME',
    fileName: 'michael-brooks-resume.docx',
    fileSizeKb: 245,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'Rachel Kim',
    uploadedAt: '2026-06-15T09:40:00Z',
    status: 'PROCESSING',
  },
] as const satisfies readonly MockDocument[];

export function getDocumentsForCandidate(candidateId: number): readonly MockDocument[] {
  return documents.filter((d) => d.candidateId === candidateId);
}

export type Documents = typeof documents;
