import type { MockEvaluation } from './types.js';

export const evaluations = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    evaluatorName: 'David Chen',
    skillCommunity: 'Full-Stack Development',
    status: 'COMPLETED',
    recommendation: 'STRONG_HIRE',
    overallScore: 92,
    technicalScore: 95,
    communicationScore: 88,
    completedAt: '2026-06-14T17:00:00Z',
    notes: 'Exceptional React architecture knowledge. Led whiteboard session on micro-frontend patterns.',
  },
  {
    id: 2,
    candidateId: 2,
    candidateName: 'James Okoro',
    evaluatorName: 'Sarah Mitchell',
    skillCommunity: 'DevOps & Cloud',
    status: 'COMPLETED',
    recommendation: 'STRONG_HIRE',
    overallScore: 94,
    technicalScore: 96,
    communicationScore: 90,
    completedAt: '2026-06-08T16:30:00Z',
    notes: 'Deep Kubernetes troubleshooting. Designed a zero-downtime migration plan in 45 minutes.',
  },
  {
    id: 3,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    evaluatorName: 'Dr. Alan Wright',
    skillCommunity: 'Machine Learning',
    status: 'COMPLETED',
    recommendation: 'HIRE',
    overallScore: 87,
    technicalScore: 90,
    communicationScore: 84,
    completedAt: '2026-05-22T15:00:00Z',
    notes: 'Strong ML fundamentals. Production deployment experience verified.',
  },
  {
    id: 4,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    evaluatorName: 'Kevin O\'Brien',
    skillCommunity: 'Cybersecurity',
    status: 'IN_PROGRESS',
    recommendation: null,
    overallScore: null,
    technicalScore: null,
    communicationScore: null,
    completedAt: null,
    notes: 'Technical assessment scheduled for July 2. Identity verification complete.',
  },
  {
    id: 5,
    candidateId: 8,
    candidateName: 'Daniel Kowalski',
    evaluatorName: 'David Chen',
    skillCommunity: 'Full-Stack Development',
    status: 'DRAFT',
    recommendation: null,
    overallScore: null,
    technicalScore: null,
    communicationScore: null,
    completedAt: null,
    notes: 'Awaiting scheduling. Backend-focused profile — frontend eval pending.',
  },
  {
    id: 6,
    candidateId: 10,
    candidateName: 'Raj Patel',
    evaluatorName: 'Sarah Mitchell',
    skillCommunity: 'DevOps & Cloud',
    status: 'COMPLETED',
    recommendation: 'HIRE',
    overallScore: 89,
    technicalScore: 91,
    communicationScore: 86,
    completedAt: '2026-06-12T14:00:00Z',
    notes: 'Excellent Rust and Go skills. Strong distributed systems background.',
  },
] as const satisfies readonly MockEvaluation[];

export type Evaluations = typeof evaluations;
