import type { MockInterview } from './types.js';

export const interviews = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    clientId: 1,
    clientName: 'Stripe',
    type: 'TECHNICAL',
    status: 'COMPLETED',
    scheduledAt: '2026-06-16T14:00:00Z',
    durationMinutes: 90,
    interviewer: 'Marcus Lee (Stripe Engineering)',
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    notes: 'Strong performance. Client requested final panel interview.',
  },
  {
    id: 2,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    clientId: 1,
    clientName: 'Stripe',
    type: 'PANEL',
    status: 'SCHEDULED',
    scheduledAt: '2026-07-02T15:00:00Z',
    durationMinutes: 60,
    interviewer: 'Stripe Payments Leadership',
    meetingUrl: 'https://meet.google.com/klm-nopq-rst',
    notes: 'Final round with VP Engineering and two staff engineers.',
  },
  {
    id: 3,
    candidateId: 2,
    candidateName: 'James Okoro',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    type: 'VIDEO',
    status: 'CONFIRMED',
    scheduledAt: '2026-07-03T10:00:00Z',
    durationMinutes: 45,
    interviewer: 'Angela Torres (BesTal) + JPM Cloud Team',
    meetingUrl: 'https://teams.microsoft.com/l/meetup-join/19%3ameeting',
    notes: 'Intro call before technical deep-dive.',
  },
  {
    id: 4,
    candidateId: 4,
    candidateName: 'Carlos Mendez',
    clientId: 5,
    clientName: 'Airbnb',
    type: 'TECHNICAL',
    status: 'REQUESTED',
    scheduledAt: null,
    durationMinutes: 60,
    interviewer: 'Airbnb Mobile Platform Team',
    meetingUrl: null,
    notes: 'Awaiting client availability for week of July 7.',
  },
  {
    id: 5,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    clientId: 4,
    clientName: 'Spotify',
    type: 'FINAL',
    status: 'COMPLETED',
    scheduledAt: '2026-05-28T13:00:00Z',
    durationMinutes: 45,
    interviewer: 'Spotify ML Leadership',
    meetingUrl: null,
    notes: 'Offer extended. Candidate accepted deployment.',
  },
  {
    id: 6,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    type: 'HR',
    status: 'RESCHEDULED',
    scheduledAt: '2026-07-08T11:00:00Z',
    durationMinutes: 30,
    interviewer: 'JPM HR Business Partner',
    meetingUrl: 'https://zoom.us/j/9876543210',
    notes: 'Rescheduled from July 1 due to client conflict.',
  },
] as const satisfies readonly MockInterview[];

export type Interviews = typeof interviews;
