import type { MockNotification } from './types.js';

export const notifications = [
  {
    id: 1,
    type: 'INTERVIEW',
    title: 'Interview scheduled',
    message: 'Panel interview for Alexandra Petrov at Stripe is scheduled for Jul 2, 2026 at 3:00 PM UTC.',
    status: 'READ',
    channel: 'IN_APP',
    userId: 2,
    createdAt: '2026-06-25T14:05:00Z',
    readAt: '2026-06-25T14:10:00Z',
  },
  {
    id: 2,
    type: 'SHORTLIST',
    title: 'New shortlist shared',
    message: 'BesTal shared "DevOps Staff — JPMorgan Cloud Migration" with 2 candidates for your review.',
    status: 'DELIVERED',
    channel: 'EMAIL',
    userId: 8,
    createdAt: '2026-06-06T09:00:00Z',
    readAt: null,
  },
  {
    id: 3,
    type: 'BACKGROUND_CHECK',
    title: 'Background check cleared',
    message: 'Comprehensive background check for Alexandra Petrov returned CLEAR via Checkr.',
    status: 'READ',
    channel: 'IN_APP',
    userId: 2,
    createdAt: '2026-06-18T14:30:00Z',
    readAt: '2026-06-18T15:00:00Z',
  },
  {
    id: 4,
    type: 'DEPLOYMENT',
    title: 'Deployment started',
    message: 'Priya Sharma deployment at Spotify is now ACTIVE as of Jun 1, 2026.',
    status: 'READ',
    channel: 'IN_APP',
    userId: 2,
    createdAt: '2026-06-01T08:00:00Z',
    readAt: '2026-06-01T08:15:00Z',
  },
  {
    id: 5,
    type: 'EVALUATION',
    title: 'Evaluation completed',
    message: 'James Okoro received STRONG_HIRE recommendation from Sarah Mitchell (DevOps & Cloud).',
    status: 'SENT',
    channel: 'IN_APP',
    userId: 4,
    createdAt: '2026-06-08T16:35:00Z',
    readAt: null,
  },
  {
    id: 6,
    type: 'DOCUMENT',
    title: 'Resume uploaded',
    message: 'Daniel Kowalski uploaded a new resume. Pending recruiter review.',
    status: 'PENDING',
    channel: 'IN_APP',
    userId: 5,
    createdAt: '2026-06-30T12:00:00Z',
    readAt: null,
  },
  {
    id: 7,
    type: 'SYSTEM',
    title: 'Platform maintenance',
    message: 'Scheduled maintenance window Jul 5, 2026 02:00–04:00 UTC. Client portal may be unavailable.',
    status: 'DELIVERED',
    channel: 'EMAIL',
    userId: 1,
    createdAt: '2026-06-29T18:00:00Z',
    readAt: '2026-06-29T20:00:00Z',
  },
  {
    id: 8,
    type: 'GENERAL',
    title: 'Approval required',
    message: 'Michael Brooks security architect shortlist awaits your approval in the client portal.',
    status: 'SENT',
    channel: 'IN_APP',
    userId: 8,
    createdAt: '2026-06-28T16:45:00Z',
    readAt: null,
  },
] as const satisfies readonly MockNotification[];

export type Notifications = typeof notifications;
