import type { PublicJob } from './types.js';

export const publicJobs = [
  {
    id: 1,
    title: 'Senior Full-Stack Engineer (React/Node)',
    slug: 'senior-full-stack-engineer-react-node',
    skillCommunity: 'Full-Stack Development',
    location: 'San Francisco, CA',
    remote: true,
    engagementType: 'CONTRACT',
    rateMin: 120,
    rateMax: 160,
    currency: 'USD',
    description:
      'Lead development of a greenfield B2B SaaS platform serving Fortune 500 clients. Work with React 19, Node.js, PostgreSQL, and AWS.',
    requirements: [
      '7+ years full-stack experience',
      'Expert React and TypeScript',
      'Node.js microservices architecture',
      'AWS or GCP production experience',
    ],
    postedAt: '2026-06-15T10:00:00Z',
    applicants: 47,
  },
  {
    id: 2,
    title: 'Staff DevOps Engineer',
    slug: 'staff-devops-engineer',
    skillCommunity: 'DevOps & Cloud',
    location: 'New York, NY',
    remote: true,
    engagementType: 'CONTRACT',
    rateMin: 140,
    rateMax: 185,
    currency: 'USD',
    description:
      'Design and operate Kubernetes-based infrastructure for a high-traffic fintech platform. Terraform, GitOps, and observability at scale.',
    requirements: [
      '8+ years DevOps/SRE experience',
      'Kubernetes in production (EKS/GKE)',
      'Terraform and Infrastructure as Code',
      'CI/CD pipeline design (GitHub Actions, ArgoCD)',
    ],
    postedAt: '2026-06-18T14:30:00Z',
    applicants: 31,
  },
  {
    id: 3,
    title: 'Principal Data Engineer',
    slug: 'principal-data-engineer',
    skillCommunity: 'Data Engineering',
    location: 'Austin, TX',
    remote: false,
    engagementType: 'PERMANENT',
    rateMin: 180000,
    rateMax: 220000,
    currency: 'USD',
    description:
      'Build real-time data pipelines processing 2B+ events daily. Spark, Kafka, Snowflake, and dbt in a modern data stack.',
    requirements: [
      '10+ years data engineering',
      'Spark and Kafka at scale',
      'Snowflake or BigQuery expertise',
      'Data modeling and governance',
    ],
    postedAt: '2026-06-20T09:00:00Z',
    applicants: 22,
  },
  {
    id: 4,
    title: 'Senior Machine Learning Engineer',
    slug: 'senior-machine-learning-engineer',
    skillCommunity: 'Machine Learning',
    location: 'Seattle, WA',
    remote: true,
    engagementType: 'CONTRACT',
    rateMin: 150,
    rateMax: 200,
    currency: 'USD',
    description:
      'Deploy production ML models for personalization and search ranking. PyTorch, MLflow, and feature stores.',
    requirements: [
      '6+ years ML engineering',
      'Production model deployment experience',
      'Python, PyTorch or TensorFlow',
      'MLOps tooling (MLflow, Kubeflow)',
    ],
    postedAt: '2026-06-22T11:00:00Z',
    applicants: 38,
  },
  {
    id: 5,
    title: 'Lead Mobile Engineer (iOS/Android)',
    slug: 'lead-mobile-engineer',
    skillCommunity: 'Mobile Development',
    location: 'Chicago, IL',
    remote: true,
    engagementType: 'FREELANCE',
    rateMin: 110,
    rateMax: 145,
    currency: 'USD',
    description:
      'Own mobile architecture for a consumer health app with 5M+ downloads. React Native, native modules, and App Store optimization.',
    requirements: [
      '8+ years mobile development',
      'React Native or Flutter expert',
      'App Store and Play Store release experience',
      'Performance profiling and optimization',
    ],
    postedAt: '2026-06-25T16:00:00Z',
    applicants: 19,
  },
  {
    id: 6,
    title: 'Security Architect',
    slug: 'security-architect',
    skillCommunity: 'Cybersecurity',
    location: 'Washington, DC',
    remote: true,
    engagementType: 'CONTRACT',
    rateMin: 160,
    rateMax: 210,
    currency: 'USD',
    description:
      'Define security architecture for a federal cloud migration. Zero-trust, FedRAMP compliance, and threat modeling.',
    requirements: [
      'CISSP or equivalent certification',
      'Cloud security (AWS/Azure)',
      'FedRAMP or SOC 2 experience',
      'Penetration testing coordination',
    ],
    postedAt: '2026-06-28T08:00:00Z',
    applicants: 14,
  },
] as const satisfies readonly PublicJob[];

export type PublicJobs = typeof publicJobs;
