import type { MockSalesDeal } from './types.js';

export const salesDeals = [
  {
    id: 1,
    clientId: 1,
    clientName: 'Stripe',
    title: 'Staff Full-Stack Engineers (3)',
    stage: 'NEGOTIATION',
    value: 450000,
    currency: 'USD',
    owner: 'Sarah Chen',
    expectedCloseDate: '2026-07-15',
    lastActivity: '2026-06-28',
  },
  {
    id: 2,
    clientId: 3,
    clientName: 'JPMorgan Chase',
    title: 'Platform Engineering Team',
    stage: 'WON',
    value: 680000,
    currency: 'USD',
    owner: 'Sarah Chen',
    expectedCloseDate: '2026-06-01',
    lastActivity: '2026-06-02',
  },
  {
    id: 3,
    clientId: 6,
    clientName: 'Meta',
    title: 'ML Engineers — Ads Platform',
    stage: 'PROPOSAL',
    value: 520000,
    currency: 'USD',
    owner: 'David Park',
    expectedCloseDate: '2026-08-30',
    lastActivity: '2026-06-25',
  },
  {
    id: 4,
    clientId: 4,
    clientName: 'Spotify',
    title: 'Senior ML Engineer Extension',
    stage: 'WON',
    value: 198000,
    currency: 'USD',
    owner: 'David Park',
    expectedCloseDate: '2026-06-01',
    lastActivity: '2026-05-28',
  },
  {
    id: 5,
    clientId: 2,
    clientName: 'Shopify',
    title: 'UX Design Team (2)',
    stage: 'QUALIFIED',
    value: 240000,
    currency: 'USD',
    owner: 'Sarah Chen',
    expectedCloseDate: '2026-09-15',
    lastActivity: '2026-06-20',
  },
  {
    id: 6,
    clientId: 7,
    clientName: 'Coinbase',
    title: 'DevOps Staff Augmentation',
    stage: 'PROSPECT',
    value: 320000,
    currency: 'USD',
    owner: 'David Park',
    expectedCloseDate: '2026-10-01',
    lastActivity: '2026-06-18',
  },
] as const satisfies readonly MockSalesDeal[];

export type SalesDeals = typeof salesDeals;
