/** Prisma-aligned types for frontend — mirrors apps/api/prisma/schema.prisma */

export type SchemaCandidateSkill = {
  readonly id: number;
  readonly candidateId: number;
  readonly skillCommunityId: number;
  readonly skillCommunityName: string;
  readonly proficiencyLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'EXPERT';
  readonly yearsExperience: number | null;
  readonly isPrimary: boolean;
  readonly notes: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaCandidate = {
  readonly id: number;
  readonly organizationId: number;
  readonly primarySkillCommunityId: number | null;
  readonly resumeDocumentId: number | null;
  readonly profileImageDocumentId: number | null;
  readonly introVideoDocumentId: number | null;
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
  readonly phone: string | null;
  readonly status: 'NEW' | 'ACTIVE' | 'INACTIVE' | 'PLACED' | 'DO_NOT_CONTACT';
  readonly visibility: 'INTERNAL_ONLY' | 'CLIENT_VISIBLE' | 'HIDDEN';
  readonly approvalStatus: 'PENDING' | 'APPROVED' | 'REJECTED';
  readonly source: 'DIRECT' | 'REFERRAL' | 'JOB_BOARD' | 'LINKEDIN' | 'AGENCY' | 'INTERNAL' | 'OTHER';
  readonly headline: string | null;
  readonly summary: string | null;
  readonly location: string | null;
  readonly yearsExperience: number | null;
  readonly availableFrom: string | null;
  readonly expectedRate: number | null;
  readonly currency: string | null;
  readonly linkedinUrl: string | null;
  readonly publishedAt: string | null;
  readonly hiddenAt: string | null;
  readonly approvedAt: string | null;
  readonly approvedById: number | null;
  readonly approvedByName: string | null;
  readonly rejectedAt: string | null;
  readonly rejectedById: number | null;
  readonly rejectedByName: string | null;
  readonly rejectionReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly photoUrl: string;
  readonly skills: readonly SchemaCandidateSkill[];
};

export type SchemaClient = {
  readonly id: number;
  readonly organizationId: number;
  readonly accountManagerId: number | null;
  readonly accountManagerName: string | null;
  readonly name: string;
  readonly slug: string;
  readonly status: 'PROSPECT' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
  readonly industry: string | null;
  readonly website: string | null;
  readonly contactEmail: string | null;
  readonly contactPhone: string | null;
  readonly addressLine1: string | null;
  readonly addressLine2: string | null;
  readonly city: string | null;
  readonly state: string | null;
  readonly postalCode: string | null;
  readonly country: string | null;
  readonly notes: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly logoUrl: string;
  readonly activeDeployments: number;
  readonly totalSpend: number;
};

export type SchemaDocument = {
  readonly id: number;
  readonly organizationId: number;
  readonly uploadedById: number;
  readonly uploadedByName: string;
  readonly entityType: string;
  readonly entityId: number;
  readonly kind: string;
  readonly fileName: string;
  readonly originalName: string;
  readonly s3Key: string;
  readonly s3Bucket: string;
  readonly mimeType: string;
  readonly fileSize: number;
  readonly status: 'PENDING' | 'UPLOADED' | 'VERIFIED' | 'REJECTED' | 'ARCHIVED';
  readonly description: string | null;
  readonly verifiedAt: string | null;
  readonly rejectedAt: string | null;
  readonly rejectReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaDeployment = {
  readonly id: number;
  readonly organizationId: number;
  readonly candidateId: number;
  readonly candidateName: string;
  readonly clientId: number;
  readonly clientName: string;
  readonly createdById: number;
  readonly createdByName: string;
  readonly status: 'PENDING' | 'ACTIVE' | 'COMPLETED' | 'TERMINATED' | 'ON_HOLD';
  readonly placementType: 'CONTRACT' | 'PERMANENT' | 'TEMP_TO_PERM' | 'FREELANCE';
  readonly roleTitle: string;
  readonly startDate: string | null;
  readonly endDate: string | null;
  readonly billingRate: number | null;
  readonly payRate: number | null;
  readonly currency: string | null;
  readonly workLocation: string | null;
  readonly notes: string | null;
  readonly terminatedAt: string | null;
  readonly terminateReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaTrialRequest = {
  readonly id: number;
  readonly organizationId: number;
  readonly candidateId: number;
  readonly candidateName: string;
  readonly clientId: number;
  readonly clientName: string;
  readonly deploymentId: number | null;
  readonly requestedById: number;
  readonly requestedByName: string;
  readonly status: 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
  readonly roleTitle: string | null;
  readonly startDate: string | null;
  readonly endDate: string | null;
  readonly durationDays: number | null;
  readonly feedback: string | null;
  readonly outcome: string | null;
  readonly approvedAt: string | null;
  readonly rejectedAt: string | null;
  readonly rejectReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaInterviewRequest = {
  readonly id: number;
  readonly organizationId: number;
  readonly candidateId: number;
  readonly candidateName: string;
  readonly clientId: number;
  readonly clientName: string;
  readonly shortlistId: number | null;
  readonly requestedById: number;
  readonly requestedByName: string;
  readonly assignedToId: number | null;
  readonly assignedToName: string | null;
  readonly type: string;
  readonly status: string;
  readonly scheduledAt: string | null;
  readonly durationMinutes: number | null;
  readonly timezone: string | null;
  readonly location: string | null;
  readonly meetingLink: string | null;
  readonly notes: string | null;
  readonly feedback: string | null;
  readonly completedAt: string | null;
  readonly cancelledAt: string | null;
  readonly cancelReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaEvaluation = {
  readonly id: number;
  readonly organizationId: number;
  readonly candidateId: number;
  readonly candidateName: string;
  readonly clientId: number | null;
  readonly clientName: string | null;
  readonly evaluatorId: number;
  readonly evaluatorName: string;
  readonly status: 'DRAFT' | 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  readonly recommendation: 'STRONG_HIRE' | 'HIRE' | 'NEUTRAL' | 'NO_HIRE' | 'STRONG_NO_HIRE' | null;
  readonly overallScore: number | null;
  readonly technicalScore: number | null;
  readonly softSkillScore: number | null;
  readonly summary: string | null;
  readonly strengths: string | null;
  readonly weaknesses: string | null;
  readonly evaluatedAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaBackgroundCheck = {
  readonly id: number;
  readonly organizationId: number;
  readonly candidateId: number;
  readonly candidateName: string;
  readonly requestedById: number;
  readonly requestedByName: string;
  readonly type: string;
  readonly status: string;
  readonly provider: string | null;
  readonly externalReferenceId: string | null;
  readonly resultSummary: string | null;
  readonly initiatedAt: string | null;
  readonly completedAt: string | null;
  readonly expiresAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaShortlist = {
  readonly id: number;
  readonly organizationId: number;
  readonly clientId: number;
  readonly clientName: string;
  readonly createdById: number;
  readonly createdByName: string;
  readonly title: string;
  readonly description: string | null;
  readonly status: 'DRAFT' | 'ACTIVE' | 'CLOSED' | 'ARCHIVED';
  readonly roleTitle: string | null;
  readonly dueDate: string | null;
  readonly closedAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};

export type SchemaUser = {
  readonly id: number;
  readonly email: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly phone: string | null;
  readonly isActive: boolean;
  readonly lastLoginAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly role: 'ADMIN' | 'RECRUITER' | 'SALES' | 'CLIENT';
  readonly organizationId: number;
  readonly photoUrl: string;
};

export type SchemaOrganization = {
  readonly id: number;
  readonly name: string;
  readonly slug: string;
  readonly isActive: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly memberCount: number;
  readonly clientCount: number;
  readonly candidateCount: number;
};

export type SchemaAuditLog = {
  readonly id: number;
  readonly organizationId: number | null;
  readonly actorId: number | null;
  readonly actorName: string | null;
  readonly action: string;
  readonly resourceType: string;
  readonly resourceId: number | null;
  readonly description: string | null;
  readonly metadata: Record<string, unknown> | null;
  readonly ipAddress: string | null;
  readonly userAgent: string | null;
  readonly createdAt: string;
};

export type SchemaNotification = {
  readonly id: number;
  readonly organizationId: number | null;
  readonly userId: number;
  readonly type: string;
  readonly channel: 'IN_APP' | 'EMAIL' | 'SMS';
  readonly status: string;
  readonly title: string;
  readonly body: string;
  readonly actionUrl: string | null;
  readonly metadata: Record<string, unknown> | null;
  readonly sentAt: string | null;
  readonly readAt: string | null;
  readonly failedAt: string | null;
  readonly failureReason: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
};
