import type { MockScreeningResult } from './types.js';

export const screeningResults = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    runAt: '2026-05-18T10:30:00Z',
    modelVersion: 'bestal-screen-v2.4',
    overallScore: 94,
    skillsMatch: 96,
    experienceMatch: 92,
    communicationScore: 91,
    riskLevel: 'LOW',
    recommendation: 'STRONG_PASS',
    flags: [],
    summary:
      'Excellent match for staff-level full-stack roles. Strong React, Node.js, and payments domain experience.',
  },
  {
    id: 2,
    candidateId: 2,
    candidateName: 'James Okoro',
    runAt: '2026-04-30T14:00:00Z',
    modelVersion: 'bestal-screen-v2.4',
    overallScore: 89,
    skillsMatch: 91,
    experienceMatch: 88,
    communicationScore: 86,
    riskLevel: 'LOW',
    recommendation: 'PASS',
    flags: ['Verify Kubernetes certification date'],
    summary: 'Strong DevOps profile with proven cloud infrastructure experience at scale.',
  },
  {
    id: 3,
    candidateId: 3,
    candidateName: 'Priya Sharma',
    runAt: '2026-06-02T09:15:00Z',
    modelVersion: 'bestal-screen-v2.4',
    overallScore: 96,
    skillsMatch: 98,
    experienceMatch: 95,
    communicationScore: 93,
    riskLevel: 'LOW',
    recommendation: 'STRONG_PASS',
    flags: [],
    summary: 'Top-tier ML engineer. Deep experience in recommendation systems and MLOps.',
  },
  {
    id: 4,
    candidateId: 4,
    candidateName: 'Sofia Martinez',
    runAt: '2026-06-08T11:45:00Z',
    modelVersion: 'bestal-screen-v2.4',
    overallScore: 87,
    skillsMatch: 90,
    experienceMatch: 84,
    communicationScore: 88,
    riskLevel: 'LOW',
    recommendation: 'PASS',
    flags: [],
    summary: 'Solid UX design portfolio with enterprise product experience.',
  },
  {
    id: 5,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    runAt: '2026-06-16T08:20:00Z',
    modelVersion: 'bestal-screen-v2.4',
    overallScore: 72,
    skillsMatch: 78,
    experienceMatch: 70,
    communicationScore: 68,
    riskLevel: 'MEDIUM',
    recommendation: 'REVIEW',
    flags: ['Gap in employment 2024–2025', 'Limited recent cloud experience'],
    summary: 'Potential fit for mid-level backend roles. Manual review recommended before client visibility.',
  },
  {
    id: 7,
    candidateId: 7,
    candidateName: 'Fatima Al-Rashid',
    runAt: '2026-05-25T15:00:00Z',
    modelVersion: 'bestal-screen-v2.3',
    overallScore: 91,
    skillsMatch: 93,
    experienceMatch: 89,
    communicationScore: 90,
    riskLevel: 'LOW',
    recommendation: 'STRONG_PASS',
    flags: [],
    summary: 'Excellent frontend engineer with design systems expertise.',
  },
] as const satisfies readonly MockScreeningResult[];

export function getScreeningForCandidate(candidateId: number): MockScreeningResult | undefined {
  return screeningResults.find((s) => s.candidateId === candidateId);
}

export type ScreeningResults = typeof screeningResults;
