import type { MockSkillCommunity } from './types.js';

export const skillCommunities = [
  {
    id: 1,
    name: 'Full-Stack Development',
    slug: 'full-stack-development',
    description: 'React, Node.js, TypeScript, and modern web architecture specialists.',
    candidateCount: 2840,
    activeJobs: 156,
    avgRate: 135,
    currency: 'USD',
    icon: 'code',
    featured: true,
  },
  {
    id: 2,
    name: 'DevOps & Cloud',
    slug: 'devops-cloud',
    description: 'Kubernetes, Terraform, AWS, GCP, and site reliability engineering experts.',
    candidateCount: 1920,
    activeJobs: 98,
    avgRate: 155,
    currency: 'USD',
    icon: 'cloud',
    featured: true,
  },
  {
    id: 3,
    name: 'Data Engineering',
    slug: 'data-engineering',
    description: 'Spark, Kafka, Snowflake, dbt, and real-time pipeline architects.',
    candidateCount: 980,
    activeJobs: 64,
    avgRate: 160,
    currency: 'USD',
    icon: 'database',
    featured: true,
  },
  {
    id: 4,
    name: 'Machine Learning',
    slug: 'machine-learning',
    description: 'PyTorch, TensorFlow, NLP, computer vision, and MLOps practitioners.',
    candidateCount: 760,
    activeJobs: 52,
    avgRate: 165,
    currency: 'USD',
    icon: 'brain',
    featured: true,
  },
  {
    id: 5,
    name: 'Mobile Development',
    slug: 'mobile-development',
    description: 'React Native, Flutter, Swift, and Kotlin mobile engineers.',
    candidateCount: 640,
    activeJobs: 41,
    avgRate: 125,
    currency: 'USD',
    icon: 'smartphone',
    featured: false,
  },
  {
    id: 6,
    name: 'Cybersecurity',
    slug: 'cybersecurity',
    description: 'Security architects, penetration testers, and compliance specialists.',
    candidateCount: 420,
    activeJobs: 28,
    avgRate: 175,
    currency: 'USD',
    icon: 'shield',
    featured: true,
  },
  {
    id: 7,
    name: 'Product Design',
    slug: 'product-design',
    description: 'UX/UI designers, design system leads, and user research experts.',
    candidateCount: 380,
    activeJobs: 22,
    avgRate: 110,
    currency: 'USD',
    icon: 'palette',
    featured: false,
  },
  {
    id: 8,
    name: 'QA & Test Automation',
    slug: 'qa-test-automation',
    description: 'Cypress, Playwright, Selenium, and quality engineering leaders.',
    candidateCount: 290,
    activeJobs: 18,
    avgRate: 105,
    currency: 'USD',
    icon: 'check-circle',
    featured: false,
  },
  {
    id: 9,
    name: 'Blockchain',
    slug: 'blockchain',
    description: 'Solidity, Ethereum, smart contract auditing, and DeFi protocol developers.',
    candidateCount: 180,
    activeJobs: 12,
    avgRate: 150,
    currency: 'USD',
    icon: 'link',
    featured: false,
  },
] as const satisfies readonly MockSkillCommunity[];

export type SkillCommunities = typeof skillCommunities;
