import type { MockTrial } from './types.js';

export const trials = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Alexandra Petrov',
    clientId: 1,
    clientName: 'Stripe',
    title: 'Staff Full-Stack Engineer — Payments',
    status: 'IN_PROGRESS',
    startDate: '2026-06-16',
    endDate: '2026-06-30',
    rate: 155,
    payRate: 115,
    billRate: 155,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: 'Strong React performance. Client requested extension.',
    recruiter: 'Rachel Kim',
  },
  {
    id: 2,
    candidateId: 4,
    candidateName: 'Sofia Martinez',
    clientId: 2,
    clientName: 'Shopify',
    title: 'Senior UX Designer — Checkout',
    status: 'SCHEDULED',
    startDate: '2026-07-07',
    endDate: '2026-07-21',
    rate: 130,
    payRate: 95,
    billRate: 130,
    currency: 'USD',
    hoursPerWeek: 32,
    pilotType: '32_HOUR',
    feedback: null,
    recruiter: 'Tom Bradley',
  },
  {
    id: 3,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    clientId: 7,
    clientName: 'Coinbase',
    title: 'Security Engineer — Infrastructure',
    status: 'IN_PROGRESS',
    startDate: '2026-06-23',
    endDate: '2026-07-07',
    rate: 165,
    payRate: 120,
    billRate: 165,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: null,
    recruiter: 'Angela Torres',
  },
  {
    id: 4,
    candidateId: 8,
    candidateName: 'Daniel Kowalski',
    clientId: 4,
    clientName: 'Spotify',
    title: 'Backend Engineer — Recommendations API',
    status: 'COMPLETED',
    startDate: '2026-05-19',
    endDate: '2026-06-02',
    rate: 140,
    payRate: 100,
    billRate: 140,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: 'Converted to full deployment. Excellent API design skills.',
    recruiter: 'Rachel Kim',
  },
  {
    id: 5,
    candidateId: 9,
    candidateName: 'Yuki Tanaka',
    clientId: 5,
    clientName: 'Airbnb',
    title: 'iOS Engineer — Host Experience',
    status: 'EXTENDED',
    startDate: '2026-06-09',
    endDate: '2026-07-09',
    rate: 145,
    payRate: 105,
    billRate: 145,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: 'Client extended trial by 2 weeks for final review.',
    recruiter: 'Tom Bradley',
  },
  {
    id: 6,
    candidateId: 11,
    candidateName: 'Amara Okafor',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    title: 'Quant Developer — Risk Models',
    status: 'CANCELLED',
    startDate: '2026-06-02',
    endDate: '2026-06-16',
    rate: 175,
    payRate: 130,
    billRate: 175,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: 'Client paused hiring freeze. Candidate re-queued.',
    recruiter: 'Angela Torres',
  },
  {
    id: 9,
    candidateId: 2,
    candidateName: 'James Okoro',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    title: 'Staff DevOps Engineer — Cloud Migration',
    status: 'IN_PROGRESS',
    startDate: '2026-06-20',
    endDate: '2026-07-04',
    rate: 175,
    payRate: 130,
    billRate: 175,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: null,
    recruiter: 'Angela Torres',
  },
  {
    id: 10,
    candidateId: 6,
    candidateName: 'Michael Brooks',
    clientId: 3,
    clientName: 'JPMorgan Chase',
    title: 'Security Architect — FedRAMP',
    status: 'REQUESTED',
    startDate: '2026-07-14',
    endDate: '2026-07-28',
    rate: 190,
    payRate: 140,
    billRate: 190,
    currency: 'USD',
    hoursPerWeek: 20,
    pilotType: '20_HOUR',
    feedback: null,
    recruiter: 'Angela Torres',
  },
  {
    id: 7,
    candidateId: 12,
    candidateName: 'Lucas Fernandez',
    clientId: 1,
    clientName: 'Stripe',
    title: 'Data Engineer — Fraud Detection',
    status: 'SCHEDULED',
    startDate: '2026-07-14',
    endDate: '2026-07-28',
    rate: 150,
    payRate: 110,
    billRate: 150,
    currency: 'USD',
    hoursPerWeek: 20,
    pilotType: '20_HOUR',
    feedback: null,
    recruiter: 'Rachel Kim',
  },
  {
    id: 8,
    candidateId: 5,
    candidateName: 'Emily Nakamura',
    clientId: 5,
    clientName: 'Airbnb',
    title: 'Staff Data Engineer — Analytics',
    status: 'COMPLETED',
    startDate: '2026-04-01',
    endDate: '2026-04-15',
    rate: 170,
    payRate: 125,
    billRate: 170,
    currency: 'USD',
    hoursPerWeek: 40,
    pilotType: '40_HOUR',
    feedback: 'Successful trial — moved to active deployment.',
    recruiter: 'Tom Bradley',
  },
] as const satisfies readonly MockTrial[];

export type Trials = typeof trials;
