import type { MockUser } from './types.js';

const avatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=1565C0&color=fff&size=128`;

export const users = [
  {
    id: 1,
    email: 'admin@bestal.com',
    firstName: 'Jordan',
    lastName: 'Hayes',
    role: 'ADMIN',
    isActive: true,
    lastLoginAt: '2026-06-30T08:45:00Z',
    photoUrl: avatar('Jordan Hayes'),
    organizationId: 1,
  },
  {
    id: 2,
    email: 'rachel.kim@bestal.com',
    firstName: 'Rachel',
    lastName: 'Kim',
    role: 'RECRUITER',
    isActive: true,
    lastLoginAt: '2026-06-30T09:12:00Z',
    photoUrl: avatar('Rachel Kim'),
    organizationId: 1,
  },
  {
    id: 3,
    email: 'tom.bradley@bestal.com',
    firstName: 'Tom',
    lastName: 'Bradley',
    role: 'RECRUITER',
    isActive: true,
    lastLoginAt: '2026-06-29T17:30:00Z',
    photoUrl: avatar('Tom Bradley'),
    organizationId: 1,
  },
  {
    id: 4,
    email: 'angela.torres@bestal.com',
    firstName: 'Angela',
    lastName: 'Torres',
    role: 'SALES',
    isActive: true,
    lastLoginAt: '2026-06-30T07:55:00Z',
    photoUrl: avatar('Angela Torres'),
    organizationId: 1,
  },
  {
    id: 5,
    email: 'david.chen@bestal.com',
    firstName: 'David',
    lastName: 'Chen',
    role: 'RECRUITER',
    isActive: true,
    lastLoginAt: '2026-06-28T14:20:00Z',
    photoUrl: avatar('David Chen'),
    organizationId: 1,
  },
  {
    id: 6,
    email: 'sarah.mitchell@bestal.com',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    role: 'RECRUITER',
    isActive: true,
    lastLoginAt: '2026-06-30T10:00:00Z',
    photoUrl: avatar('Sarah Mitchell'),
    organizationId: 1,
  },
  {
    id: 7,
    email: 'platform-admin@bestal.com',
    firstName: 'Chris',
    lastName: 'Nguyen',
    role: 'ADMIN',
    isActive: true,
    lastLoginAt: '2026-06-29T22:15:00Z',
    photoUrl: avatar('Chris Nguyen'),
    organizationId: 1,
  },
  {
    id: 8,
    email: 'sarah.chen@stripe.com',
    firstName: 'Sarah',
    lastName: 'Chen',
    role: 'CLIENT',
    isActive: true,
    lastLoginAt: '2026-06-30T11:00:00Z',
    photoUrl: avatar('Sarah Chen'),
    organizationId: 1,
  },
] as const satisfies readonly MockUser[];

export type Users = typeof users;
